### ISSUE TITLE
It appears that you cannot rename a project with white spaces

### ISSUE THREAD

**Issue by Proper-Job** [ytbryan/rename#1]
I tried to rename a Project with white space in the title and this was the output, with the files untouched:

./rename
WARNING: Close your Xcode before proceeding.

Press enter to replace: Test Project with TestProject (Type q to quit)

usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Done. Project name synchronised.
You might want to change the project's scheme too. Go to Manage Scheme.

**Comment by ytbryan** [comment]
yup. it's true that the script does not accept project name with white space for now.
