### ISSUE TITLE
cannot load highline/import

### ISSUE THREAD

**Issue by xanderbuck** [ytbryan/rename#2]
When I try to run the rename script I get this error in the console. Any suggestions?

Also my console doesn't recognize the "update install" command?

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- highline/import (LoadError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in`require'
    from /Users/******/Downloads/rename-master-2/example/rename:3:in `<main>'

**Comment by ytbryan** [comment]
Type this command to install highline

sudo gem install highline

Do the same If you encounter other dependency problems
